print('*Escreva um programa que leia um valor em metros e o exiba convertido em cm e mm*')
print('')
n1 = float(input('Qual é sua altura em metros? '))
print('Você tem {} centímetros ou {} milímetros'.format(n1*100,n1*1000))
print('Você tem {n1} centímetros ou {n1} milímetros'.f)
